### ISSUE TITLE
Cannot call method 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by AuthorProxy** [es-analysis/plato#133]
Windows 8.1. NPM 1.4.28. Throw error on start.

> plato -r -d ./

C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\plato\lib\util.js:15
  var lastSlash = files[0].lastIndexOf(path.sep);
                           ^
TypeError: Cannot call method 'lastIndexOf' of undefined
    at Object.exports.findCommonBase (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\plato\lib\util.js:15:28)
    at Object.exports.inspect (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\plato\lib\plato.js:81:29)
    at Object.exports.exec (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\plato\lib\cli.js:48:9)
    at Object.<anonymous> (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\plato\bin\plato:19:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by victor-homyakov** [comment]
https://github.com/es-analysis/plato/blob/master/lib/util.js#L14 should be

```js
if (!files || files.length === 0) return '';
```

**Comment by petraplatz** [comment]
the same issue here, are you going to fix it ?

**Comment by felixzapata** [comment]
I have the same error. Are you going to fix it?

**Comment by mycaule** [comment]
Same problem running on Windows 7.

**Comment by eknath-iyer** [comment]
Same issue in Windows 8.1 with node 0.12.5

**Comment by JaggyGT** [comment]
@victor-homyakov that fix causes it to find no files for me, though it does complete without error.

**Comment by wagnerjs** [comment]
Same problem in OSX 10.10.5 with node v0.12.4

**Comment by nithin-ideas2it** [comment]
Am using Ubuntu 12.04

I just tried with:

plato -r -d report "folder-path"

eg: 
>plato -r -d report /home/project/src/

then a folder 'report' has been created with files listed below.

>ls 
assets  display.html  files  index.html  report.history.js  report.history.json  report.js  report.json

opened the index.html with browser, I saw the beautiful Analysis-report.

**Comment by wagnerjs** [comment]
I agree with u.

Issue occurs when the source files folder does not exist in directory.

**Comment by nithin-ideas2it** [comment]
yes, exactly.

**Comment by mcpDESIGNS** [comment]
Even after creating the folder manually, I still don't see any results from plato with:

    plato -r -d report "src"

**Comment by the-simian** [comment]
I know what causes this issue, and I fixed it on a fork I have. Its when our glob has no files in it, tries to find the first element of an empty array.
https://www.npmjs.com/package/es6-plato
