### ISSUE TITLE
If you don't specify files it throw exception and show stacktrace

### ISSUE THREAD

**Issue by jcubic** [es-analysis/plato#64]
This is what you see if you call `plato -d <DIR>`

```
/usr/lib/node_modules/plato/lib/util.js:14
  var prefixlen = first.length;
                       ^
TypeError: Cannot read property 'length' of undefined
    at Object.exports.findCommonBase (/usr/lib/node_modules/plato/lib/util.js:14:24)
    at Object.exports.inspect (/usr/lib/node_modules/plato/lib/plato.js:69:29)
    at Object.exports.exec (/usr/lib/node_modules/plato/lib/cli.js:47:9)
    at Object.<anonymous> (/usr/lib/node_modules/plato/bin/plato:19:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by ilanbiala** [comment]
@jcubic is this still an issue?
